#!/usr/bin/env bash
# cepa health check — read-only. Prints a fact report for /cepa:setup to
# interpret. Never modifies anything. Run from the project root.
set -u

ok()   { printf 'OK   %s\n' "$1"; }
miss() { printf 'MISS %s\n' "$1"; }
info() { printf 'INFO %s\n' "$1"; }

echo "== cepa health check: $(pwd) =="

# --- config file -----------------------------------------------------------
if [ -f cepa.local.md ]; then
  ok "cepa.local.md exists"
  for section in "## Stack" "## Review Agents (Active)" "## Autonomy" "## Integrations"; do
    if grep -q "^${section}" cepa.local.md; then ok "section: ${section}"; else miss "section: ${section}"; fi
  done
  grep -q "^## Compliance" cepa.local.md && ok "section: ## Compliance" || info "section: ## Compliance absent (fine if no compliance regime)"
  # Count only lines inside the Review Agents section (bounded by the next
  # ## heading) — a fixed -A window bleeds into ## Autonomy/## Integrations.
  roster_count=$(awk '/^## Review Agents/{f=1;next} /^## /{f=0} f' cepa.local.md | grep -c '^- [a-z!]' || true)
  info "roster: ${roster_count} agent lines"
  grep -q '<!-- generated by /cepa:setup fix' cepa.local.md && info "config is machine-generated and unverified (remove the marker after review)"
else
  miss "cepa.local.md"
fi

# --- scaffold dirs ---------------------------------------------------------
for d in docs/plans docs/solutions todos memory; do
  [ -d "$d" ] && ok "dir: $d/" || miss "dir: $d/"
done
[ -f memory/tasks.md ] && ok "file: memory/tasks.md" || miss "file: memory/tasks.md"
if [ -d docs/solutions ]; then
  info "solution docs: $(find docs/solutions -name '*.md' -not -name '.gitkeep' 2>/dev/null | wc -l | tr -d ' ')"
fi
if [ -d todos ]; then
  info "review files: $(ls todos/review-*.md 2>/dev/null | wc -l | tr -d ' ')"
fi

# --- grounding provider (optional) ------------------------------------------
# Facts only; /cepa:setup interprets (cepa:grounding skill is the contract).
# Section-scoped awk, same reason as the roster count above.
check_ignore_leg() {
  # distinguish "not ignored" (exit 1) from git itself erroring (exit >1) —
  # a wrong MISS diagnosis sends the human to edit .gitignore when git is broken
  git check-ignore -q "$1" 2>/dev/null
  case $? in
    0) ok "grounding: $1 is git-ignored" ;;
    1) miss "grounding: $1 NOT git-ignored (refresh would dirty the tree — provider degrades)" ;;
    *) miss "grounding: git check-ignore errored on $1 (git problem, not an ignore problem)" ;;
  esac
}
if [ -f cepa.local.md ] && awk '/^## Integrations/{f=1;next} /^## /{f=0} f' cepa.local.md | grep -q '^grounding:'; then
  info "grounding provider configured"
  command -v graphify >/dev/null 2>&1 && ok "grounding: graphify binary on PATH" || miss "grounding: graphify binary NOT on PATH (reviews silently run grep-only)"
  if [ -e graphify-out ] && [ ! -d graphify-out ]; then
    miss "grounding: graphify-out exists but is NOT a directory (collision — remove it before any graph build)"
  else
    [ -f graphify-out/graph.json ] && ok "grounding: graphify-out/graph.json exists" || miss "grounding: graphify-out/graph.json missing (initial build is a human action)"
  fi
  if git rev-parse --git-dir >/dev/null 2>&1; then
    check_ignore_leg graphify-out
    [ -e graph.json ] && check_ignore_leg graph.json
  else
    miss "grounding: not a git repo — ignore legs unverifiable (availability leg 3 fails at runtime; provider degrades every run)"
  fi
  grep -q "^## Compliance" cepa.local.md && info "grounding configured in a COMPLIANCE repo — graphify-out arms the global graphify skill's LLM doc pass; human policy needed (cepa:grounding skill)"
elif [ -f cepa.local.md ] && grep -qi 'grounding' cepa.local.md; then
  # mentioned but not at the sanctioned location (column-0 'grounding:' under
  # ## Integrations) — setup report and runtime LLM read could diverge
  info "grounding mentioned in cepa.local.md but not parseable at the sanctioned location (column-0 'grounding:' under ## Integrations) — see cepa:grounding skill"
fi

# --- git -------------------------------------------------------------------
if git rev-parse --git-dir >/dev/null 2>&1; then
  ok "git repo (branch: $(git branch --show-current))"
  git check-ignore docs/plans >/dev/null 2>&1 && info "docs/plans is GITIGNORED (plans stay local)" || ok "docs/plans is tracked"
  git check-ignore todos >/dev/null 2>&1 && info "todos/ is GITIGNORED" || ok "todos/ is tracked"
  # exists-on-disk but never committed = scaffold that vanishes on any other
  # checkout; report it as its own state, never as plain OK
  for d in docs/solutions todos memory; do
    if [ -d "$d" ] && ! git check-ignore "$d" >/dev/null 2>&1 && [ -z "$(git ls-files "$d" | head -1)" ]; then
      info "dir $d/ exists but has NO tracked files (uncommitted scaffold)"
    fi
  done
else
  miss "not a git repository"
fi

# --- CI --------------------------------------------------------------------
# The script reports FACTS about workflows; classifying a real PR gate vs a
# deploy job that happens to build is the command's job (read the matched
# files). GitHub accepts .yml AND .yaml; ERE alternation is POSIX-portable.
wf_files=$(find .github/workflows -maxdepth 1 \( -name '*.yml' -o -name '*.yaml' \) 2>/dev/null | sort)
if [ -n "$wf_files" ]; then
  ok "CI workflows: $(echo "$wf_files" | xargs -n1 basename | tr '\n' ' ')"
  test_cmd_files=$(echo "$wf_files" | xargs grep -El \
    'pytest|tox|manage\.py test|npm (run )?test|yarn test|pnpm (run )?test|vitest|jest|astro build|npm run build' \
    2>/dev/null || true)
  if [ -n "$test_cmd_files" ]; then
    info "workflow(s) mention a test/build command — VERIFY they gate PRs, not just deploy: $(echo "$test_cmd_files" | tr '\n' ' ')"
    echo "$test_cmd_files" | xargs grep -l 'pull_request' >/dev/null 2>&1 \
      && info "at least one matched workflow triggers on pull_request" \
      || miss "no matched workflow triggers on pull_request (push/deploy only — not a PR gate)"
  else
    miss "no workflow mentions a test or build command (deploy/notify only)"
  fi
elif [ -d .github/workflows ]; then
  miss "workflows dir exists but contains no workflow files"
else
  miss "no .github/workflows — no CI gate"
fi

# --- plugin version drift --------------------------------------------------
IP="$HOME/.claude/plugins/installed_plugins.json"
if ! command -v python3 >/dev/null 2>&1; then
  info "python3 unavailable — skipping installed-version check"
elif [ -f "$IP" ]; then
  installed=$(python3 - "$IP" <<'PYEOF'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    print("PARSE-ERROR"); raise SystemExit
try:
    print(d["plugins"]["cepa@cepa"][0]["version"])
except (KeyError, IndexError, TypeError):
    print("NOT-INSTALLED")
PYEOF
)
  case "$installed" in
    PARSE-ERROR)   info "could not parse installed_plugins.json — format may have changed" ;;
    NOT-INSTALLED) miss "cepa plugin not found in installed_plugins.json" ;;
    *)             info "installed cepa plugin: v${installed}" ;;
  esac
else
  info "installed_plugins.json not found (non-standard install)"
fi

echo "== end health check =="
